server.port=8084
logging.threshold.console=warn
spring.datasource.url=jdbc:postgresql://localhost:5432/prj1_dev
spring.datasource.username=postgres
spring.datasource.password=huydz091
logging.file.name=logs/dev.log