server.port=8083
logging.threshold.console=warn
spring.datasource.url=jdbc:postgresql://localhost:5432/prj1_prod
spring.datasource.username=postgres
spring.datasource.password=huydz091
logging.file.name=logs/prod.log