server.port=8080
logging.level.root=INFO

spring.datasource.url=jdbc:postgresql://localhost:5432/prj1_prod

spring.datasource.username=postgres
spring.datasource.password=huydz091
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=150MB
jwt.signerKey = Kuezs6rQaEq0mSjSoRE6NCXKUEE+OAzdbF9p1q7oxpVGqdz3neJXlgt48+v2+Pwm\\n
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
logging.file.name=logs/prod.log