server.port=8084
logging.threshold.console=warn
spring.datasource.url=jdbc:postgresql://db:5432/prj1_dev
spring.datasource.username=postgres
spring.datasource.password=huydz091
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=150MB
jwt.signerKey = Kuezs6rQaEq0mSjSoRE6NCXKUEE+OAzdbF9p1q7oxpVGqdz3neJXlgt48+v2+Pwm\\n
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
logging.file.name=logs/dev.log