spring.application.name=prj1

server.port=8085
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/prj1
spring.datasource.username=postgres
spring.datasource.password=huydz091

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=150MB